# Cloud Build 配置文件 - cloudbuild.yaml
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/hugo-tour-dashboard', '.']

  # 推送镜像到Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/hugo-tour-dashboard']

  # 部署到Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'hugo-tour-dashboard'
      - '--image'
      - 'gcr.io/$PROJECT_ID/hugo-tour-dashboard'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-west1'
      - '--allow-unauthenticated'
      - '--port=3000'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--set-env-vars=NODE_ENV=production,ELEVENLABS_DEFAULT_MODEL_ID=eleven_flash_v2_5,OPENROUTER_MODEL=deepseek/deepseek-chat-v3-0324:free,S3_REGION=us-west-1,NUXT_PUBLIC_SITE_URL=https://hugo-tour-dashboard-icmbf6lkoa-uw.a.run.app'
      - '--update-secrets=ELEVENLABS_API_KEY=projects/$PROJECT_ID/secrets/elevenlabs_api_key:latest'
    
# 定义需要使用的镜像
images:
  - 'gcr.io/$PROJECT_ID/hugo-tour-dashboard'

# 超时设置（可选）
timeout: '1800s'
