# Cloud Build 配置文件 - cloudbuild.yaml
steps:
  # 构建Docker镜像
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/hugo-tour-dashboard', '.']

  # 推送镜像到Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/hugo-tour-dashboard']

  # 部署到Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'hugo-tour-dashboard'
      - '--image'
      - 'gcr.io/$PROJECT_ID/hugo-tour-dashboard'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-west1'
      - '--allow-unauthenticated'
      - '--port=3000'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--set-env-vars=NODE_ENV=production'
    
# 定义需要使用的镜像
images:
  - 'gcr.io/$PROJECT_ID/hugo-tour-dashboard'

# 超时设置（可选）
timeout: '1800s'
