services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ARG_SUPABASE_URL=${SUPABASE_URL}
        - ARG_SUPABASE_KEY=${SUPABASE_KEY}
        - ARG_SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
        - GIT_CLONE_URL=${GIT_CLONE_URL}
        - ARG_ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
        - ARG_ELEVENLABS_DEFAULT_MODEL_ID=${ELEVENLABS_DEFAULT_MODEL_ID}
        - ARG_OPENROUTER_MODEL=${OPENROUTER_MODEL}
        - ARG_OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
        - ARG_S3_ACESS_ID=${S3_ACESS_ID}
        - ARG_S3_SECRET_KEY=${S3_SECRET_KEY}
        - ARG_S3_ENDDPOINT=${S3_ENDDPOINT}
        - ARG_S3_REGION=${S3_REGION}
        - ARG_NUXT_PUBLIC_SITE_URL=${NUXT_PUBLIC_SITE_URL}
    container_name: hugo-tour-dashboard-app
    restart: unless-stopped
    env_file:
      - .env
    # 也可以在这里直接定义环境变量，它们会覆盖 .env 文件中的同名变量
    # environment:
    #   NODE_ENV: production # 通常在 Dockerfile 中设置
    ports:
      # 将主机的 3000 端口映射到容器的 3000 端口
      # 格式: "HOST_PORT:CONTAINER_PORT"
      - "3000:3000"
    # (可选) 如果需要持久化数据，可以添加 volumes
    # volumes:
    #   - ./some-data:/app/data