services:
  app:
    build:
      context: .
      # Dockerfile 名称，如果不是 'Dockerfile'，请修改这里
      dockerfile: Dockerfile
    container_name: hugo-tour-dashboard-app
    restart: unless-stopped
    # 从 .env 文件加载环境变量
    env_file:
      - .env
    # 也可以在这里直接定义环境变量，它们会覆盖 .env 文件中的同名变量
    # environment:
    #   NODE_ENV: production # 通常在 Dockerfile 中设置
    ports:
      # 将主机的 3000 端口映射到容器的 3000 端口
      # 格式: "HOST_PORT:CONTAINER_PORT"
      - "3000:3000"
    # (可选) 如果需要持久化数据，可以添加 volumes
    # volumes:
    #   - ./some-data:/app/data